export const DATE_FORMAT = {
    YYYYMMDD: 'YYYYMMDD',
    YYYYMD: 'YYYYMD',
    YYYYMMDD_JA: 'YYYY年MM月DD日',
    YYYYMMDD_SLASH: 'YYYY/MM/DD',
    YYYYMMDD_HYPHEN: 'YYYY-MM-DD',
    YYYYMD_JA: 'YYYY年M月D日',
    YYYYMD_SLASH: 'YYYY/M/D',
    YYYYMD_HYPHEN: 'YYYY-M-D',
    YYYYMM: 'YYYYMM',
    YYYYM: 'YYYYM',
    YYYYMM_JA: 'YYYY年MM月',
    YYYYMM_SLASH: 'YYYY/MM',
    YYYYMM_HYPHEN: 'YYYY-MM',
    YYYYM_JA: 'YYYY年M月',
    YYYYM_SLASH: 'YYYY/M',
    YYYYM_HYPHEN: 'YYYY-M',
    YYYY: 'YYYY',
    YYYY_JA: 'YYYY年',
    MM: 'MM',
    MM_JA: 'MM月',
    M: 'M',
    M_JA: 'M月',
    DD: 'DD',
    DD_JA: 'DD日',
    D: 'D',
    D_JA: 'D日'
} as const;

export const TIME_FORMAT = {
    HHmmss: 'HHmmss',
    Hms: 'Hms',
    HHmmss_JA: 'HH時mm分ss秒',
    HHmmss_CORON: 'HH:mm:ss',
    Hms_JA: 'H時m分s秒',
    Hms_CORON: 'H:m:s',
    HHmm: 'HHmm',
    Hm: 'Hm',
    HHmm_JA: 'HH時mm分',
    HHmm_CORON: 'HH:mm',
    Hm_JA: 'H時m分',
    Hm_CORON: 'H:m'
} as const;
